const productList = [
    {"id": 10, "catg": "macc", "imgUrl": "IMG_3312 2.JPG", "title": "Macarrons", "subTitle": "21 pieces", "price": "1000.00"},
    {"id": 20, "catg": "macc", "imgUrl": "IMG_0945.JPG", "title": "Macarrons", "subTitle": "40 pieces",  "price": "1800.00"},
    {"id": 30, "catg": "macc", "imgUrl": "IMG_3314.JPG", "title": "Macarrons", "subTitle": "20 pieces",  "price": "1000.00"},
    {"id": 40, "catg": "cake", "imgUrl": "IMG_1404.JPG", "title": "Red velvet", "subTitle": "16 pieces",  "price": "850.00"},
    {"id": 50, "catg": "cake", "imgUrl": "IMG_0947.JPG", "title": "Red velvet", "subTitle": "20 pieces",  "price": "1000.00"},
    {"id": 60, "catg": "cake", "imgUrl": "IMG_0619.JPG", "title": "Red velvet", "subTitle": "35 pieces",  "price": "1400.00"},
    {"id": 70, "catg": "tart", "imgUrl": "IMG_2746.JPG", "title": "Mini tarts", "subTitle": "12 pieces",  "price": "850.00"},
    {"id": 80, "catg": "cake", "imgUrl": "IMG_5546.JPG", "title": "Almond salted caramel", "subTitle": "16 pieces",  "price": "850.00"},
    {"id": 90, "catg": "cake", "imgUrl": "IMG_0946.JPG", "title": "Almond salted caramel", "subTitle": "20 pieces",  "price": "1000.00"},
    {"id": 100, "catg": "cake", "imgUrl": "IMG_0940 2.JPG", "title": "Young coconut, Thai Tea, Orange, Soft chocolate cake", "subTitle": "loaf",  "price": "250.00"},
    {"id": 110, "catg": "cake", "imgUrl": "IMG_1582.JPG", "title": "Young coconut, Soft chocolate cake", "subTitle": "loaf",  "price": "250.00"},
    {"id": 120, "catg": "cake", "imgUrl": "IMG_0941 2.JPG", "title": "Mini Coconut, Orange, Soft chocolate cup cake", "subTitle": "cup",  "price": "90.00"},
    {"id": 130, "catg": "cake", "imgUrl": "IMG_4235.JPG", "title": "Young coconut cake", "subTitle": "3 pounds",  "price": "1400.00"},
    {"id": 140, "catg": "cake", "imgUrl": "IMG_0950.JPG", "title": "Soft chocolate cake", "subTitle": "3 pounds",  "price": "1400.00"},
    {"id": 150, "catg": "cake", "imgUrl": "IMG_4236.JPG", "title": "Strawberry short cake", "subTitle": "3 pounds",  "price": "1500.00"},
    {"id": 160, "catg": "cake", "imgUrl": "IMG_9422.JPG", "title": "Lemon cake", "subTitle": "3 pieces",  "price": "350.00"},
    {"id": 170, "catg": "cake", "imgUrl": "IMG_9438.JPG", "title": "Cheese cake", "subTitle": "piece",  "price": "150.00"},
    {"id": 180, "catg": "tart", "imgUrl": "IMG_0956.JPG", "title": "Assorted tarts", "subTitle": "piece",  "price": "160.00"},
    {"id": 190, "catg": "cake", "imgUrl": "TOFFEE_BANOFFEE.JPG", "title": "Toffee Banoffee", "subTitle": "piece",  "price": "150.00"},
    {"id": 200, "catg": "ginger", "imgUrl": "IMG_3317.JPG", "title": "Sugar free ginger powder", "subTitle": "set",  "price": "1400.00"},
    {"id": 210, "catg": "ginger", "imgUrl": "IMG_3316.JPG", "title": "Healthy gift set", "subTitle": "set",  "price": "950.00"},
    {"id": 220, "catg": "tea", "imgUrl": "IMG_3351.JPG", "title": "Premium Celon tea", "subTitle": "500 g",  "price": "350.00"},
    {"id": 230, "catg": "tea", "imgUrl": "CELON_TEA_01.JPG", "title": "Premium Celon tea", "subTitle": "500 g",  "price": "350.00"},
    {"id": 240, "catg": "tea", "imgUrl": "CELON_TEA_02.JPG", "title": "Premium Celon tea", "subTitle": "500 g",  "price": "350.00"},
    {"id": 250, "catg": "ginger", "imgUrl": "IMG_3346.JPG", "title": "Sugar free giger powder", "subTitle": "300 gr",  "price": "350.00"},
    {"id": 260, "catg": "cake", "imgUrl": "IMG_7472.JPG", "title": "Tiramisu", "subTitle": "piece",  "price": "150.00"},
    {"id": 270, "catg": "tart", "imgUrl": "IMG_7469.JPG", "title": "Tart", "subTitle": "piece",  "price": "160.00"},
    {"id": 280, "catg": "madln", "imgUrl": "IMG_9443.JPG", "title": "Madeleine", "subTitle": "piece",  "price": "50.00"},
    {"id": 290, "catg": "madln", "imgUrl": "MADELEINE_01.JPG", "title": "Madeleine", "subTitle": "piece",  "price": "50.00"},
    {"id": 300, "catg": "madln", "imgUrl": "IMG_7478.JPG", "title": "Madeleine", "subTitle": "12 pieces",  "price": "550.00"},
    {"id": 310, "catg": "tea", "imgUrl": "IMG_9432.JPG", "title": "Thai tea", "subTitle": "1 liter",  "price": "250.00"},
    {"id": 320, "catg": "tea", "imgUrl": "LEMON_TEA.JPG", "title": "Lemon tea", "subTitle": "1 liter",  "price": "250.00"},
    {"id": 330, "catg": "tea", "imgUrl": "TAIWAN_TEA.JPG", "title": "Taiwan tea", "subTitle": "1 liter",  "price": "250.00"},
    {"id": 340, "catg": "cookie", "imgUrl": "IMG_7489.JPG", "title": "Matcha crunchy almond", "subTitle": "piece",  "price": "250.00"},
    {"id": 350, "catg": "cookie", "imgUrl": "IMG_7490.JPG", "title": "Caramel crunchy almond", "subTitle": "piece",  "price": "250.00"},
    {"id": 360, "catg": "cookie", "imgUrl": "CRUNCHY_ALMOND.JPG", "title": "Mixed crunchy almond", "subTitle": "piece",  "price": "250.00"},
    {"id": 370, "catg": "cookie", "imgUrl": "IMG_7484.JPG", "title": "Dairy free corn flakes", "subTitle": "piece",  "price": "200.00"},
    {"id": 380, "catg": "cookie", "imgUrl": "CARAMEL_CORN_FLAKES.JPG", "title": "Caramel corn flakes", "subTitle": "piece",  "price": "200.00"},
    {"id": 390, "catg": "cookie", "imgUrl": "CORN_FLAKES_COOKIES.JPG", "title": "Corn flakes cookies", "subTitle": "piece",  "price": "200.00"},
  ]
  
  const categories = [
    { "title": "All",               "value": "" },
    { "title": "Maccarons",         "value": "macc" },
    { "title": "Cake", "value":     "cake" },
    { "title": "Tart", "value":     "tart" },
    { "title": "Almond", "value":    "almond" },
    { "title": "Madeleine", "value": "madln" },
    { "title": "Ginger", "value":    "ginger" },
    { "title": "Tea", "value":       "tea" },
    { "title": "Gift set",           "value": "set" }
  ]
  